.TH "MCAL/DIO/DIO_Private.h" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCAL/DIO/DIO_Private.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORTA\fP   (*(volatile \fBu8\fP *)(0x3B)) /*PORTA Macro Definition*/"
.br
.ti -1c
.RI "#define \fBDDRA\fP   (*(volatile \fBu8\fP *)(0x3A)) /*DDRA  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPINA\fP   (*(volatile \fBu8\fP *)(0x39)) /*PINA  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPORTB\fP   (*(volatile \fBu8\fP *)(0x38)) /*PORTB Macro Definition*/"
.br
.ti -1c
.RI "#define \fBDDRB\fP   (*(volatile \fBu8\fP *)(0x37)) /*DDRB  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPINB\fP   (*(volatile \fBu8\fP *)(0x36)) /*PINB  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPORTC\fP   (*(volatile \fBu8\fP *)(0x35)) /*PORTC Macro Definition*/"
.br
.ti -1c
.RI "#define \fBDDRC\fP   (*(volatile \fBu8\fP *)(0x34)) /*DDRC  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPINC\fP   (*(volatile \fBu8\fP *)(0x33)) /*PINC  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPORTD\fP   (*(volatile \fBu8\fP *)(0x32)) /*PORTD Macro Definition*/"
.br
.ti -1c
.RI "#define \fBDDRD\fP   (*(volatile \fBu8\fP *)(0x31)) /*DDRD  Macro Definition*/"
.br
.ti -1c
.RI "#define \fBPIND\fP   (*(volatile \fBu8\fP *)(0x30)) /*PIND  Macro Definition*/"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDRA   (*(volatile \fBu8\fP *)(0x3A)) /*DDRA  Macro Definition*/"

.SS "#define DDRB   (*(volatile \fBu8\fP *)(0x37)) /*DDRB  Macro Definition*/"

.SS "#define DDRC   (*(volatile \fBu8\fP *)(0x34)) /*DDRC  Macro Definition*/"

.SS "#define DDRD   (*(volatile \fBu8\fP *)(0x31)) /*DDRD  Macro Definition*/"

.SS "#define PINA   (*(volatile \fBu8\fP *)(0x39)) /*PINA  Macro Definition*/"

.SS "#define PINB   (*(volatile \fBu8\fP *)(0x36)) /*PINB  Macro Definition*/"

.SS "#define PINC   (*(volatile \fBu8\fP *)(0x33)) /*PINC  Macro Definition*/"

.SS "#define PIND   (*(volatile \fBu8\fP *)(0x30)) /*PIND  Macro Definition*/"

.SS "#define PORTA   (*(volatile \fBu8\fP *)(0x3B)) /*PORTA Macro Definition*/"

.SS "#define PORTB   (*(volatile \fBu8\fP *)(0x38)) /*PORTB Macro Definition*/"

.SS "#define PORTC   (*(volatile \fBu8\fP *)(0x35)) /*PORTC Macro Definition*/"

.SS "#define PORTD   (*(volatile \fBu8\fP *)(0x32)) /*PORTD Macro Definition*/"

.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
