.TH "Register_32Bit" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Register_32Bit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <STD_TYPES\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit0\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit1\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit2\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit3\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit4\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit5\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit6\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit7\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit8\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit9\fP: 1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit10\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit11\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit12\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit13\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit14\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit15\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit16\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit17\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit18\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit19\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit20\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit21\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit22\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit23\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit24\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit25\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit26\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit27\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit28\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit29\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit30\fP:1"
.br
.ti -1c
.RI "   \fBu8\fP \fBBit31\fP:1"
.br
.ti -1c
.RI "} \fBBitAccess\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBFourByteAccess\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP Register_32Bit::Bit0"

.SS "\fBu8\fP Register_32Bit::Bit1"

.SS "\fBu8\fP Register_32Bit::Bit10"

.SS "\fBu8\fP Register_32Bit::Bit11"

.SS "\fBu8\fP Register_32Bit::Bit12"

.SS "\fBu8\fP Register_32Bit::Bit13"

.SS "\fBu8\fP Register_32Bit::Bit14"

.SS "\fBu8\fP Register_32Bit::Bit15"

.SS "\fBu8\fP Register_32Bit::Bit16"

.SS "\fBu8\fP Register_32Bit::Bit17"

.SS "\fBu8\fP Register_32Bit::Bit18"

.SS "\fBu8\fP Register_32Bit::Bit19"

.SS "\fBu8\fP Register_32Bit::Bit2"

.SS "\fBu8\fP Register_32Bit::Bit20"

.SS "\fBu8\fP Register_32Bit::Bit21"

.SS "\fBu8\fP Register_32Bit::Bit22"

.SS "\fBu8\fP Register_32Bit::Bit23"

.SS "\fBu8\fP Register_32Bit::Bit24"

.SS "\fBu8\fP Register_32Bit::Bit25"

.SS "\fBu8\fP Register_32Bit::Bit26"

.SS "\fBu8\fP Register_32Bit::Bit27"

.SS "\fBu8\fP Register_32Bit::Bit28"

.SS "\fBu8\fP Register_32Bit::Bit29"

.SS "\fBu8\fP Register_32Bit::Bit3"

.SS "\fBu8\fP Register_32Bit::Bit30"

.SS "\fBu8\fP Register_32Bit::Bit31"

.SS "\fBu8\fP Register_32Bit::Bit4"

.SS "\fBu8\fP Register_32Bit::Bit5"

.SS "\fBu8\fP Register_32Bit::Bit6"

.SS "\fBu8\fP Register_32Bit::Bit7"

.SS "\fBu8\fP Register_32Bit::Bit8"

.SS "\fBu8\fP Register_32Bit::Bit9"

.SS "struct { \&.\&.\&. }  Register_32Bit::BitAccess"

.SS "\fBu32\fP Register_32Bit::FourByteAccess"


.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
