.TH "HAL/SSD/SSD_Program.c" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL/SSD/SSD_Program.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./LED/LED_Interface\&.h'\fP
.br
\fC#include 'SSD_Private\&.h'\fP
.br
\fC#include 'SSD_Interface\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBSSD_u8Init\fP (\fBu8\fP u8Reg)"
.br
.RI "Prototype : u8 \fBSSD_u8Init(u8 u8Reg)\fP; Description : Initialize one 7-Segment of 8 LEDs on specific port\&. "
.ti -1c
.RI "\fBu8\fP \fBSSD_u8DisplayNumber\fP (\fBu8\fP u8Reg, \fBu8\fP u8DisblayNumber)"
.br
.RI "Prototype : u8 \fBSSD_u8DisplayNumber(u8 u8Reg,u8 u8DisblayNumber)\fP; Description : Display a number on a given 7-segment\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBu8\fP SSD_u8DisplayNumber (\fBu8\fP u8Reg, \fBu8\fP u8DisblayNumber)"

.PP
Prototype : u8 \fBSSD_u8DisplayNumber(u8 u8Reg,u8 u8DisblayNumber)\fP; Description : Display a number on a given 7-segment\&. 
.PP
\fBParameters\fP
.RS 4
\fIu8Reg\fP Register: takes only MDIO_PORTA,MDIO_PORTB,MDIO_PORTC,MDIO_PORTD 
.br
\fIu8DisblayNumber\fP Number : takes only from 0 to 9 
.RE
.PP
\fBReturns\fP
.RS 4
u8 number for error handling (0) means no error, (1) means Undefined PORT, (2) means Display Number out of range error 
.RE
.PP

.SS "\fBu8\fP SSD_u8Init (\fBu8\fP u8Reg)"

.PP
Prototype : u8 \fBSSD_u8Init(u8 u8Reg)\fP; Description : Initialize one 7-Segment of 8 LEDs on specific port\&. 
.PP
\fBParameters\fP
.RS 4
\fIu8Reg\fP Register: takes only MDIO_PORTA,MDIO_PORTB,MDIO_PORTC,MDIO_PORTD 
.RE
.PP
\fBReturns\fP
.RS 4
u8 number used for error handling (0) means no error,(1) means Undefined PORT Argument 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
