.TH "HAL/SSD/SSD_Private.h" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL/SSD/SSD_Private.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./LIB/STD_TYPES\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBu8\fP \fBSSD_u8SevenSegArray\fP [10] ={0xc0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBu8\fP SSD_u8SevenSegArray[10] ={0xc0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90}"

.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
