.TH "LIB/STD_MACROS.h" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LIB/STD_MACROS.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSET_BIT\fP(REG,  BIT_NUM)   ((REG)|=(1<<(BIT_NUM)))"
.br
.ti -1c
.RI "#define \fBCLEAR_BIT\fP(REG,  BIT_NUM)   ((REG)&=(~(1<<(BIT_NUM))))"
.br
.ti -1c
.RI "#define \fBTOGGLE_BIT\fP(REG,  BIT_NUM)   ((REG)^=(1<<(BIT_NUM)))"
.br
.ti -1c
.RI "#define \fBGET_BIT\fP(REG,  BIT_NUM)   ((REG)>>(BIT_NUM))&(0X01)"
.br
.ti -1c
.RI "#define \fBIS_BIT_SET\fP(REG,  BIT_NUM)   ((REG)   &  (1<< BIT_NUM))"
.br
.ti -1c
.RI "#define \fBIS_BIT_CLEAR\fP(REG,  BIT_NUM)   (!(\fBIS_BIT_SET\fP(REG,BIT_NUM)))"
.br
.ti -1c
.RI "#define \fBVAL\fP   1"
.br
.ti -1c
.RI "#define \fBBITCALC_ASSIGN_BIT\fP(REG,  BIT_NUM,  \fBVAL\fP)   REG=((REG)&(~(1<<(BIT_NUM))))|(\fBVAL\fP<<(BIT_NUM))"
.br
.ti -1c
.RI "#define \fBSET_BIT_VALUE\fP(REG,  BIT,  Value)   ( (Value == 0) ? ( REG &= ~(1<<BIT) ) : ( REG |= (1<<BIT) ) )"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BITCALC_ASSIGN_BIT(REG, BIT_NUM, \fBVAL\fP)   REG=((REG)&(~(1<<(BIT_NUM))))|(\fBVAL\fP<<(BIT_NUM))"

.SS "#define CLEAR_BIT(REG, BIT_NUM)   ((REG)&=(~(1<<(BIT_NUM))))"

.SS "#define GET_BIT(REG, BIT_NUM)   ((REG)>>(BIT_NUM))&(0X01)"

.SS "#define IS_BIT_CLEAR(REG, BIT_NUM)   (!(\fBIS_BIT_SET\fP(REG,BIT_NUM)))"

.SS "#define IS_BIT_SET(REG, BIT_NUM)   ((REG)   &  (1<< BIT_NUM))"

.SS "#define SET_BIT(REG, BIT_NUM)   ((REG)|=(1<<(BIT_NUM)))"

.SS "#define SET_BIT_VALUE(REG, BIT, Value)   ( (Value == 0) ? ( REG &= ~(1<<BIT) ) : ( REG |= (1<<BIT) ) )"

.SS "#define TOGGLE_BIT(REG, BIT_NUM)   ((REG)^=(1<<(BIT_NUM)))"

.SS "#define VAL   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
