.TH "LIB/STD_TYPES.h" 3 "Thu Apr 21 2022" "Version 1.0" "STOPWATCH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LIB/STD_TYPES.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBRegister_32Bit\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFALSE\fP   (0u)"
.br
.ti -1c
.RI "#define \fBTRUE\fP   (1u)"
.br
.ti -1c
.RI "#define \fBHIGH\fP   (1u)"
.br
.ti -1c
.RI "#define \fBLOW\fP   (0u)"
.br
.ti -1c
.RI "#define \fBNULL\fP   ((void *)0)"
.br
.ti -1c
.RI "#define \fBERROR_NOK\fP   (\fBu8\fP)0"
.br
.ti -1c
.RI "#define \fBERROR_OK\fP   (\fBu8\fP)1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBu8\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fBu16\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBu32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBu64\fP"
.br
.ti -1c
.RI "typedef signed char \fBs8\fP"
.br
.ti -1c
.RI "typedef signed short int \fBs16\fP"
.br
.ti -1c
.RI "typedef signed long int \fBs32\fP"
.br
.ti -1c
.RI "typedef signed long long \fBs64\fP"
.br
.ti -1c
.RI "typedef float \fBf32\fP"
.br
.ti -1c
.RI "typedef double \fBf64\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_NOK   (\fBu8\fP)0"

.SS "#define ERROR_OK   (\fBu8\fP)1"

.SS "#define FALSE   (0u)"

.SS "#define HIGH   (1u)"

.SS "#define LOW   (0u)"

.SS "#define NULL   ((void *)0)"

.SS "#define TRUE   (1u)"

.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBf32\fP"

.SS "typedef double \fBf64\fP"

.SS "typedef signed short int \fBs16\fP"

.SS "typedef signed long int \fBs32\fP"

.SS "typedef signed long long \fBs64\fP"

.SS "typedef signed char \fBs8\fP"

.SS "typedef unsigned short int \fBu16\fP"

.SS "typedef unsigned long int \fBu32\fP"

.SS "typedef unsigned long long \fBu64\fP"

.SS "typedef unsigned char \fBu8\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for STOPWATCH from the source code\&.
